# Generated by Django 4.0.5 on 2022-07-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_confirmstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_confirmd',
            field=models.BooleanField(default=False),
        ),
    ]
